# -*- coding: utf-8 -*-
"""Tugas 1 AED Kelompok 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fi-QHbYYl_7mRLavknS6WWLf3csRG7Dx

# **Tugas**

Hitung rataan, simpangan baku, skewness dan kurtosis dari

total pengeluaran rumah tangga sebulan terakhir di salah satu kabupaten/kota
proporsi pengeluaran makanan rumah tangga di salah satu kabupaten/kota
total pengeluaran rumah tangga sebulan terakhir di salah satu kabupaten/kota, masing-masing untuk rumah tangga yang memiliki mobil dan yang tidak memiliki mobil
Catatan: kabupaten/kota yang dipilih, berbeda-beda antar kelompok

Kelompok 5 AED

1. M0401241129 Yasmin Aufaahani Abdullah
2. M0401241036 Atikah Maulina
3. M0401241043 Dzulfikar Najib
4. M0401241026 Meilania Pramashara Putri Hapsari
5. M0401241135 Najwa Fachrurozi
6. M0401241130 Astra Dama

**Kota: Bandung**

Step 1:Import Library & Load Data

Import data dulu
"""

import pandas as pd
import numpy as np

# Load data
# Kenapa low_memory=False? Biar Pandas nggak protes kalau ada kolom yang isinya campur aduk (teks & angka)
df_kp = pd.read_csv('2023 Maret JABAR - SUSENAS KP BP 4.3.csv', low_memory=False)
df_kor = pd.read_csv('2023 Maret JABAR - SUSENAS KOR Rumah Tangga.csv', low_memory=False)

print("Data berhasil di-load!")

"""Step 2: Menyamakan "Kunci" dan Menggabungkan Data

Kolom URUT sebagai kunci utamanya.
"""

df_kp['URUT'] = pd.to_numeric(df_kp['URUT'], errors='coerce')
df_kor['URUT'] = pd.to_numeric(df_kor['URUT'], errors='coerce')

# Merge data (Inner Join)
# Artinya: Kita cuma ambil rumah tangga yang ada di kedua file tersebut.
df_master = pd.merge(df_kp, df_kor, on='URUT', how='inner')

print(f"Hasil gabungan punya {df_master.shape[0]} baris data.")

"""Step 3: Memilih Wilayah & Membersihkan Data

Kota Bandung (Kode: 73).

Kenapa dibersihin? Data mentah seringkali dianggap "teks" oleh Python. Kita paksa jadi angka pakai to_numeric. Kalau nggak, bakal dapet hasil NaN.
"""

# 1. Pilih Kabupaten (Misal Kota Bandung = 73)
# Sesuaikan kode ini kalau mau ganti wilayah (lihat file layout R102)
df_kab = df_master[df_master['R102_x'] == 73].copy()

# 2. Paksa kolom jadi angka. 'coerce' bakal ngubah data yang aneh jadi NaN
df_kab['EXPEND'] = pd.to_numeric(df_kab['EXPEND'], errors='coerce')
df_kab['FOOD'] = pd.to_numeric(df_kab['FOOD'], errors='coerce')
df_kab['R2001K'] = pd.to_numeric(df_kab['R2001K'], errors='coerce') # Kolom Kepemilikan Mobil

# 3. Buang data yang kosong di kolom penting
df_kab = df_kab.dropna(subset=['EXPEND', 'FOOD'])

print(f"Data Kota Bandung siap olah: {len(df_kab)} rumah tangga.")

"""Step 4:Fungsi Statistik

Membuat fungsi biar bisa di panggil berulang kali
"""

def hitung_statistik(data_series):
    # Kita hitung 4 pilar statistik deskriptif
    return pd.Series({
        'Rata-rata': data_series.mean(),
        'Simpangan Baku': data_series.std(),
        'Skewness (Kemiringan)': data_series.skew(),
        'Kurtosis (Keruncingan)': data_series.kurt()
    })

"""Step 5: Eksekusi Tugas 1, 2, dan 3"""

# --- TUGAS 1: Total Pengeluaran ---
print("--- TUGAS 1: TOTAL PENGELUARAN ---")
print(hitung_statistik(df_kab['EXPEND']))

"""1. Analisis Deskriptif Total Pengeluaran Rumah Tangga Berdasarkan data pengeluaran bulanan, ditemukan kondisi distribusi ekonomi sebagai berikut:

> **Rata-rata vs Realitas:** Meskipun rata-rata pengeluaran tercatat sebesar Rp 8.644.742, angka ini tidak merepresentasikan kondisi mayoritas masyarakat.

>**Ketimpangan Ekonomi (Disparitas):** Nilai Simpangan Baku yang mencapai Rp 9.218.992 (lebih besar dari rata-ratanya) mengindikasikan adanya variasi pengeluaran yang sangat lebar antar rumah tangga. Hal ini mencerminkan adanya kesenjangan ekonomi yang signifikan di wilayah tersebut.

> **Karakteristik Distribusi (Skewness 5,04):** Nilai kemiringan (skewness) positif yang sangat tinggi menunjukkan bahwa distribusi data menjulur ke kanan. Secara profesional, ini berarti mayoritas rumah tangga berada di kelompok pengeluaran rendah, namun nilai rata-rata terdistorsi naik akibat adanya sejumlah kecil rumah tangga dengan pengeluaran yang sangat tinggi (high-spenders).

> **Konsentrasi Data dan Outlier (Kurtosis 44,05):** Nilai kurtosis yang ekstrem menunjukkan adanya penumpukan data yang tajam di satu titik, diikuti dengan keberadaan nilai-nilai pencilan (outliers) yang banyak. Ini mengonfirmasi keberadaan kelompok elit kecil yang pola konsumsinya jauh melampaui rata-rata populasi.
"""

# --- TUGAS 2: Proporsi Makanan ---
# Kita buat variabel baru: (Duit Makan / Total Pengeluaran)
df_kab['proporsi_makanan'] = df_kab['FOOD'] / df_kab['EXPEND']
print("\n--- TUGAS 2: PROPORSI PENGELUARAN MAKANAN ---")
print(hitung_statistik(df_kab['proporsi_makanan']))

"""2. Analisis Struktur Konsumsi: Analisis terhadap proporsi pengeluaran makanan memberikan gambaran mengenai tingkat kesejahteraan wilayah berdasarkan Hukum Engel:

> **Efisiensi Konsumsi: Rata-rata proporsi pengeluaran makanan sebesar 45,7%**, menunjukkan bahwa secara umum wilayah ini telah melampaui taraf pemenuhan kebutuhan dasar (subsisten). Semakin rendah proporsi makanan, semakin besar ruang bagi rumah tangga untuk mengalokasikan dana ke kebutuhan sekunder dan investasi.

> **Keseragaman Pola Konsumsi: Simpangan baku yang rendah (0,139)**, menunjukkan bahwa pola pembagian anggaran untuk pangan cenderung homogen atau serupa di hampir seluruh lapisan masyarakat.

> **Analisis Kemiringan (Skewness -0,226):** Nilai negatif menunjukkan sedikit kemiringan ke kiri. Hal ini mengindikasikan adanya kelompok rumah tangga tertentu (kelas atas) yang proporsi pengeluaran makanannya jauh lebih rendah dibandingkan rata-rata, karena total pengeluaran mereka didominasi oleh barang-barang non-makanan.

> **Kurtosis (-0,373):** Nilainya negatif (Platykurtic): Distribusinya agak landai atau "gemuk". Nggak ada penumpukan ekstrem di satu angka tertentu. Pola pengeluaran makanan di sana cukup beragam tapi masih dalam batas wajar.
"""

# --- TUGAS 3: Berdasarkan Mobil ---
# Berdasarkan layout, R2001K: 1 = Ya (Punya), selain itu dianggap Tidak.
punya_mobil = df_kab[df_kab['R2001K'] == 1]['EXPEND']
tidak_punya = df_kab[df_kab['R2001K'] != 1]['EXPEND']

print("\n--- TUGAS 3A: PENGELUARAN (PUNYA MOBIL) ---")
print(hitung_statistik(punya_mobil))

print("\n--- TUGAS 3B: PENGELUARAN (TIDAK PUNYA MOBIL) ---")
print(hitung_statistik(tidak_punya))

"""3. Komparasi Berbasis Aset: Kepemilikan mobil digunakan sebagai proksi kekayaan untuk membedakan segmentasi gaya hidup:

> **Daya Beli: **Terdapat perbedaan signifikan dalam daya beli, di mana kelompok pemilik mobil memiliki rata-rata pengeluaran ~2,9 kali lipat (Rp 19,2 Juta) dibandingkan kelompok non-pemilik mobil (Rp 6,6 Juta).

> **Heterogenitas Kelompok:** Pemilik Mobil: Memiliki Simpangan Baku yang sangat tinggi (16,1 Juta), menunjukkan bahwa stratifikasi ekonomi di dalam kelas pemilik mobil sendiri sangatlah bervariasi (mulai dari kelas menengah hingga kelas atas).

> **Non-Pemilik Mobil:** Memiliki Kurtosis yang lebih tinggi (23,71), yang berarti data kelompok ini sangat terpusat dan homogen pada level pengeluaran yang rendah.

> **Kesimpulan Segmentasi:** Kelompok non-pemilik mobil mencerminkan kondisi ekonomi masyarakat pada umumnya yang cenderung stabil di level bawah, sementara kelompok pemilik mobil mewakili segmen ekonomi yang lebih dinamis namun dengan ketimpangan internal yang lebih besar.
"""